PassAppDev/Controllers/AdminsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using PassAppDev.Data;

using PassAppDev.Models;
using PassAppDev.Utils;
using PassAppDev.ViewModels;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace PassAppDev.Controllers
{
	[Authorize(Roles = Role.ADMIN)]
	public class AdminsController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;
		PasswordHasher<ApplicationUser> passwordHasher = new PasswordHasher<ApplicationUser>();
		public AdminsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
		{
			_context = context;
			_userManager = userManager;

		}
		public IActionResult Index()
		{
			IEnumerable<Category> categories = _context.Categories
				.Where(t=>t.Status==Enums.CategoryStatus.Pending)
					.Include(t => t.ApplicationUser)
					.ToList();
			return View(categories);
		}

		[HttpGet]
		public IActionResult Reject(int id)
		{
			var categoryInDb = _context.Categories.SingleOrDefault(t => t.Id == id);
			if (categoryInDb is null)
			{
				return NotFound();
			}
			var notification = new Notification()
			{
				ApplicationUserId = categoryInDb.ApplicationUserId,
				CategoryId = categoryInDb.Id,
				CategoryName = categoryInDb.Name,
				Decision = "REJECTED"
			};
			if (categoryInDb.OldName == null)
			{
				notification.Action = "ADDING";
				_context.Categories.Remove(categoryInDb);
			}
			else
			{
				notification.Action = "EDITTING";
				categoryInDb.Name = categoryInDb.OldName;
				categoryInDb.OldName = null;
				categoryInDb.Status = Enums.CategoryStatus.Approved;
			}
			_context.Add(notification);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}


		[HttpGet]
		public IActionResult Approve(int id)
		{
			var categoryInDb = _context.Categories.SingleOrDefault(t => t.Id == id);

			if(categoryInDb==null)
			{
				return NotFound();
			}
            var notification = new Notification()
            {
                ApplicationUserId = categoryInDb.ApplicationUserId,
                CategoryId = categoryInDb.Id,
                CategoryName = categoryInDb.Name,
				Decision = "APPROVED"
            };
			if (categoryInDb.OldName == null)
            {
				notification.Action = "ADDING";
            }
            else
            {
				notification.Action = "EDITTING";
			}
            categoryInDb.Status = Enums.CategoryStatus.Approved;
			categoryInDb.OldName = null;
			_context.Add(notification);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult ApprovedCategories()
		{
			IEnumerable<Category> categories = _context.Categories
				.Where(t => t.Status == Enums.CategoryStatus.Approved)
					.Include(t => t.ApplicationUser)
					.ToList();
			return View(categories);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var categoryInDb = _context.Categories.SingleOrDefault(t => t.Id == id);
			if (categoryInDb is null)
			{
				return NotFound();
			}
			_context.Categories.Remove(categoryInDb);
			_context.SaveChanges();
			return RedirectToAction("ApprovedCategories");
		}

		[HttpGet]
		public IActionResult Customers()
		{
			var customer = _userManager.GetUsersInRoleAsync(Role.CUSTOMER).Result;
			return View(customer);
		}

		[HttpGet]
		public IActionResult DeleteCustomer(string id) {
			var userInDb = _context.ApplicationUsers.SingleOrDefault(t => t.Id.Equals(id));
			if (userInDb is null)
			{
				return NotFound();
			}
			_context.ApplicationUsers.Remove(userInDb);
			_context.SaveChanges();
			return RedirectToAction("Customers");
		}

		[HttpGet]
		public IActionResult StoreOwners()
		{
			var storeOwner = _userManager.GetUsersInRoleAsync(Role.STOREOWNER).Result;
			return View(storeOwner);
		}

		[HttpGet]
		public IActionResult ChangeCustomerPassword(string id)
		{
			var userInDb = _context.ApplicationUsers.SingleOrDefault(t => t.Id == id);

			if (userInDb is null)
			{
				return NotFound();
			}
			
			return View(userInDb);
		}

		[HttpGet]
		public IActionResult ChangeStoreOwnerPassword(string id)
		{
			var userInDb = _context.ApplicationUsers.SingleOrDefault(t => t.Id == id);

			if (userInDb is null)
			{
				return NotFound();
			}

			return View(userInDb);
		}

		[HttpPost]
		public IActionResult ChangeCustomerPassword(ApplicationUser user)
		{
			var userInDb = _context.ApplicationUsers.SingleOrDefault(t => t.Id == user.Id);

			if (userInDb is null)
			{
				return BadRequest();
			}

			if (!ModelState.IsValid)
			{
				return View(userInDb);
			}
			
			userInDb.PasswordHash = passwordHasher.HashPassword(null, user.PasswordHash);
			_context.SaveChanges();

			return RedirectToAction("Customers");
		}

		[HttpPost]
		public IActionResult ChangeStoreOwnerPassword(ApplicationUser user)
		{
			var userInDb = _context.ApplicationUsers.SingleOrDefault(t => t.Id == user.Id);

			if (userInDb is null)
			{
				return BadRequest();
			}

			if (!ModelState.IsValid)
			{
				return View(userInDb);
			}

			if (user.PasswordHash != null)
			{
				userInDb.PasswordHash = passwordHasher.HashPassword(null, user.PasswordHash);
			}
			
			_context.SaveChanges();

			return RedirectToAction("StoreOwners");
		}
	}
}

PassAppDev/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using PassAppDev.Data;
using PassAppDev.Models;
using PassAppDev.Utils;
using PassAppDev.ViewModels;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PassAppDev.Controllers
{
	[Authorize(Roles = Role.STOREOWNER)]
	public class BooksController : Controller
	{
		private ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;
		public BooksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
		{
			_context = context;
			_userManager = userManager;
		}

		[HttpGet]
		public IActionResult Index(string keyWord)
		{

			if (!string.IsNullOrWhiteSpace(keyWord))
			{
				var result = _context.Books
					.Include(t => t.Category)
					.Where(t => t.Category.Name.Contains(keyWord)
							|| t.Title.Contains(keyWord)
					)
					.ToList();

				return View(result);
			}

			IEnumerable<Book> books = _context.Books
				.Include(t => t.Category)
				.ToList();

			return View(books);
		}

		[HttpGet]
		public IActionResult Create()
		{
			var viewModel = new BookCategoriesViewModel()
			{
				Categories = _context.Categories
					.Where(t => t.Status == Enums.CategoryStatus.Approved)
					.ToList()
			};
			return View(viewModel);
		}

		[HttpPost]
		public async Task<IActionResult> CreateAsync(BookCategoriesViewModel viewModel)
		{
			if (!ModelState.IsValid)
			{
				viewModel = new BookCategoriesViewModel
				{
					Categories = _context.Categories
						.Where(t => t.Status == Enums.CategoryStatus.Approved)
						.ToList()
				};
				return View(viewModel);
			}

			using (var memoryStream = new MemoryStream())
			{
				await viewModel.FormFile.CopyToAsync(memoryStream);

				var newBook = new Book
				{
					Title = viewModel.Book.Title,
					Author = viewModel.Book.Author,
					Price = viewModel.Book.Price,
					Description = viewModel.Book.Description,
					CategoryId = viewModel.Book.CategoryId,
					ImageData = memoryStream.ToArray()
				};

				_context.Add(newBook);
				await _context.SaveChangesAsync();
			}

			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var bookInDb = _context.Books.SingleOrDefault(t => t.Id == id);
			if (bookInDb is null)
			{
				return NotFound();
			}

			_context.Books.Remove(bookInDb);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			var bookInDb = _context.Books.SingleOrDefault(t => t.Id == id);
			if (bookInDb is null)
			{
				return NotFound();
			}

			var viewModel = new BookCategoriesViewModel
			{
				Book = bookInDb,
				Categories = _context.Categories
					.Where(t => t.Status == Enums.CategoryStatus.Approved).ToList()



			};

			ViewBag.ImageData = ConvertByteArrayToStringBase64(bookInDb.ImageData);

			return View(viewModel);

		}

		[HttpPost]
		public async Task<IActionResult> Edit(BookCategoriesViewModel viewModel)
		{
			var bookInDb = _context.Books.SingleOrDefault(t => t.Id == viewModel.Book.Id);
			if (bookInDb is null)
			{
				return BadRequest();
			}

			if (!ModelState.IsValid)
			{
				viewModel = new BookCategoriesViewModel
				{
					Book = viewModel.Book,
					Categories = _context.Categories
						.Where(t => t.Status == Enums.CategoryStatus.Approved).ToList(),
				};

				ViewBag.ImageData = ConvertByteArrayToStringBase64(bookInDb.ImageData);
				return View(viewModel);
			}
			bookInDb.Title = viewModel.Book.Title;
			bookInDb.Author = viewModel.Book.Author;
			bookInDb.Price = viewModel.Book.Price;
			bookInDb.Description = viewModel.Book.Description;
			bookInDb.CategoryId = viewModel.Book.CategoryId;


			if (viewModel.FormFile != null)
			{
				using (var memoryStream = new MemoryStream())

				{
					await viewModel.FormFile.CopyToAsync(memoryStream);

					if (memoryStream != null)
						bookInDb.ImageData = memoryStream.ToArray();
				}
				
			}
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult Details(int id)
		{
			var bookInDb = _context.Books.Include(t => t.Category)
					.SingleOrDefault(t => t.Id == id);
			if (bookInDb is null)
			{
				return NotFound();
			}

			ViewBag.ImageData = ConvertByteArrayToStringBase64(bookInDb.ImageData);
			return View(bookInDb);
		}



		[NonAction]
		private string ConvertByteArrayToStringBase64(byte[] imageArray)
		{
			string imageBase64Data = Convert.ToBase64String(imageArray);

			return string.Format("data:image/jpg;base64, {0}", imageBase64Data);
		}
	}

}

PassAppDev/Controllers/CartBooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PassAppDev.Data;
using PassAppDev.Models;
using PassAppDev.Utils;
using System;
using PassAppDev.ViewModels;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;

namespace PassAppDev.Controllers
{
	[Authorize(Roles = Role.CUSTOMER)]
	public class CartBooksController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;
		public CartBooksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
		{
			_context = context;
			_userManager = userManager;
		}

		[HttpGet]
		public IActionResult Index()
		{
			var currentUserId = _userManager.GetUserId(HttpContext.User);
			IEnumerable<CartBook> booksInCart = _context.CartBooks
					 .Include(t => t.Book)
					 .Include(t => t.ApplicationUser)
					 .Where(t => t.ApplicationUserId == currentUserId)
					 .ToList();
			return View(booksInCart);
		}

		public async Task<IActionResult> AddToCart(int id)
		{
			var bookInStore = _context.Books.SingleOrDefault(t => t.Id == id);
			var currentUserId = _userManager.GetUserId(HttpContext.User);

			var bookInCart = _context.CartBooks.SingleOrDefault(
					t => t.ApplicationUserId == currentUserId &&
					t.BookId == id);
			if (bookInCart == null)
			{
				var cartBook = new CartBook()
				{
					ApplicationUserId = currentUserId,
					BookId = id,
					Quatity = 1,
					Price = bookInStore.Price
				};
				_context.Add(cartBook);
			}
			else
			{
				bookInCart.Quatity++;
			}
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}
		public async Task<IActionResult> Delete(int id)
		{

			var bookInCart = await _context.CartBooks.SingleOrDefaultAsync(t => t.Id == id);
			if (bookInCart == null)
			{
				return NotFound();
			}

			_context.CartBooks.Remove(bookInCart);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}


		public IActionResult IncreaseQty(int id)
		{
			var cartBookInDb = _context.CartBooks.SingleOrDefault(t => t.Id==id);
			if (cartBookInDb == null)
			{
				return NotFound();
			}

			cartBookInDb.Quatity ++;
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		public IActionResult DecreaseQty(int id)
		{
			var cartBookInDb = _context.CartBooks.SingleOrDefault(t => t.Id == id);
			if (cartBookInDb == null)
			{
				return NotFound();
			}
			if (cartBookInDb.Quatity > 0)
			{
				cartBookInDb.Quatity--;
			}
			
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

PassAppDev/Controllers/StoresController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using PassAppDev.Data;

using PassAppDev.Models;
using PassAppDev.Utils;
using PassAppDev.ViewModels;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;
using static System.Net.Mime.MediaTypeNames;

namespace PassAppDev.Controllers
{
    [Authorize(Roles = Role.STOREOWNER)]
    public class StoresController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public StoresController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        public IActionResult Index()
        {

            IEnumerable<Order> orders = _context.Orders
                                .Include(t => t.ApplicationUser)
                                .ToList();
            return View(orders);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            IEnumerable<OrderedBook> orderedBooks = _context.OrderedBooks
                                                                                            .Include(t => t.Order)
                                                                                            .Include(t => t.Book)
                                                                                            .Where(t => t.OrderId == id)
                                                                                            .ToList();
            return View(orderedBooks);
        }

        public IActionResult SearchUser(string email)
        {
            var customer = _userManager.GetUsersInRoleAsync(Role.CUSTOMER).Result;


            if (!string.IsNullOrWhiteSpace(email))
            {

                var result = customer.Where(t => t.Email.Contains(email)).ToList();

                return View(result);
            }


            return View(customer);

        }
    }
}

PassAppDev/Views/Home/BookDetails.cshtml
@model Book


<div class="col-sm-6 mx-auto">
    <img class="card-img-top border-top border-right border-left" style=" object-fit:contain;"
         src="@ViewBag.ImageData"
         alt="image">
    <div class="card-body text-left border-right border-left border-bottom">
        <a asp-controller="Home" asp-action="BookDetails" asp-route-id=@Model.Id class="card-link book-title">
            <h2 class="card-title"> @Model.Title</h2>
        </a>
        <p class="card-text text-wrap text-justify">@Model.Description</p>
        <h5 class="card-text book-author">Author: @Model.Author </h5>
        <h5 class="card-text book-author">Category: @Model.Category.Name </h5>
        <h5 class="card-text book-price">Price: @Model.Price VND</h5>
        <div class="d-flex justify-content-around" style="margin-top:1rem;">
            <a asp-controller="CartBooks" asp-action="AddToCart" asp-route-id=@Model.Id class="btn btn-info float-left cart-button">
                                   <i class="bi bi-cart-plus-fill"></i> Add to cart
                             </a>

        </div>
    </div>

</div>
<div class="form-group">
    <a style="margin-top:5%; margin-left: 2%;" asp-controller="Home" asp-action="Index" class="btn btn-danger">
        Back
    </a>
</div>

PassAppDev/Views/Home/Index.cshtml
@using PassAppDev.ViewModels
@model PassAppDev.ViewModels.BookNotificationViewModel
@using PassAppDev.Utils
@{
    ViewData["Title"] = "Home Page";
}
<div class="container">

    <div class="text-center">

        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active" style="height:27vw;object-fit:cover;">
                    <img class="d-block w-100 carousel-img" src="https://tinyurl.com/5n79nb34" alt="First slide">
                </div>
                <div class="carousel-item" style="height:27vw;object-fit:cover;">
                    <img class="d-block w-100 carousel-img" src="https://tinyurl.com/5fr6zj2y" alt="Second slide">
                </div>
                <div class="carousel-item" style="height:27vw;object-fit:cover;">
                    <img class="d-block w-100 carousel-img" src="https://tinyurl.com/2hawzzdd" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        @if (!User.Identity.IsAuthenticated)
        {

            <div class="text-wrap align-content-center" style="width: 100%">
                <h1 id="greeting"></h1>
            </div>


            <div class="row card-deck">

                @foreach (var item in Model.BookViewModels)
                {
                    <div class="col-sm-4">
                        <img class="card-img-top border-top border-right border-left" style="margin-top:10%; height:65vh; object-fit:cover;"
                     src="@item.ImageUrl"
                     alt="image">
                        <div class="card-body text-left border-right border-left border-bottom">
                            <a asp-controller="Home" asp-action="BookDetails" asp-route-id=@item.Id class="card-link book-title">
                                <h2 class="card-title"> @item.Title</h2>
                            </a>
                            <h5 class="card-text text-muted book-author">Author: @item.Author </h5>
                            <h5 class="card-text text-muted book-price">Price: @item.Price VND</h5>
                            <div class="d-flex justify-content-around" style="margin-top:1rem;">
                                <a asp-controller="CartBooks" asp-action="AddToCart" asp-route-id=@item.Id class="btn btn-info rounded-pill float-left cart-button">
                                    <i class="bi bi-cart-plus-fill"></i> Buy now
                                </a>

                            </div>
                        </div>

                    </div>
                }

            </div>
        }
        else if (User.IsInRole(Role.CUSTOMER))
        {
            <div class="text-wrap align-content-center" style="width: 100%;">
                <h1 id="greeting"></h1>
                <p class="greeting-by-role">You are signing in as a @Role.CUSTOMER</p>
            </div>

            <div class="row card-deck">

                @foreach (var item in Model.BookViewModels)
                {
                    <div class="col-sm-4">
                        <img class="card-img-top border-top border-right border-left" style="margin-top:10%; height:70vh; object-fit:cover;"
                     src="@item.ImageUrl"
                     alt="image">
                        <div class="card-body text-left border-right border-left border-bottom">
                            <a asp-controller="Home" asp-action="BookDetails" asp-route-id=@item.Id class="card-link book-title">
                                <h3 class="card-title"> @item.Title</h3>
                            </a>
                            <h5 class="card-text text-muted book-author">Author: @item.Author </h5>
                            <h5 class="card-text text-muted book-price">Price: @item.Price VND</h5>
                            <div class="d-flex justify-content-around">
                                <a asp-controller="CartBooks" asp-action="AddToCart" asp-route-id=@item.Id class="btn btn-info float-left cart-button">
                                    <i class="bi bi-cart-plus-fill"></i> Add to cart
                                </a>

                            </div>
                        </div>

                    </div>
                }

            </div>
        }
        else if (User.IsInRole(Role.STOREOWNER))

        {
            <div class="text-wrap align-content-center" style="width: 100%;">
                <h1 id="greeting"></h1>

                <div class="d-flex justify-content-center">
                    <div class="dropdown">
                        <a style="font-size:2vw;"
                        id="dropdownMenuLink"
                        data-toggle="dropdown"
                        aria-haspopup="true"
                        aria-expanded="false">
                            <i class="bi bi-bell-fill"></i>
                        </a>
                        <table class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="overflow:auto; width:52vw; height:20vw;">

                            @foreach (var item in Model.Notifications)
                            {
                                <tr class="dropdown-item" style="width:50vw;">
                                    @if (item.Decision == "APPROVED")
                                    {

                                        <td class="alert alert-success text-wrap " style="width:85%;">
                                            <i class="bi bi-check-circle-fill"></i> Your request for @item.Action the category "@item.CategoryName" has been <b>@item.Decision!</b>
                                        </td>
                                        <td class="text-muted text-wrap text-cent" style="padding-left:2%;">@item.NotifiedAt.ToShortTimeString() @item.NotifiedAt.ToShortDateString()</td>
                                    }
                                    else
                                    {
                                        <td class="alert alert-danger text-wrap " style="width:85%;">
                                            <i class="bi bi-x-circle-fill"></i> Your request for @item.Action the category "@item.CategoryName" has been <b>@item.Decision!</b>

                                        </td>
                                        <td class="text-muted text-wrap text-cent" style="padding-left:2%;">@item.NotifiedAt.ToShortTimeString() @item.NotifiedAt.ToShortDateString()</td>
                                    }
                                </tr>
                            }
                        </table>
                       
                    </div>
                     <p class="greeting-by-role">You are signing in as a store owner</p>
                </div>
                

            </div>

            <a asp-controller="Books" asp-action="Index" class="btn btn-info">
                Manage Books
            </a>
            <a asp-controller="Categories" asp-action="Index" class="btn btn-info">
                Manage Categories
            </a>
            <a asp-controller="Stores" asp-action="SearchUser" class="btn btn-info">
                List of Customers
            </a>
            <a asp-controller="Stores" asp-action="Index" class="btn btn-info">
                List of Customer Orders
            </a>


        }
        else if (User.IsInRole(Role.ADMIN))
        {
             <div class="text-wrap align-content-center" style="width: 100%;">
                <h1 id="greeting"></h1>
                <p class="greeting-by-role">You are signing in as an Administrator</p>
            </div>
            <a asp-controller="Admins" asp-action="Customers" class="btn btn-info">
                Manage Customers
            </a>
            <a asp-controller="Admins" asp-action="StoreOwners" class="btn btn-info">
                Manage Store Owners
            </a>
            <a asp-controller="Admins" asp-action="Index" class="btn btn-info">
                Category Request
            </a>
        }
    </div>
</div>