PassAppDev/Controllers/CartBooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PassAppDev.Data;
using PassAppDev.Models;
using PassAppDev.Utils;
using System;
using PassAppDev.ViewModels;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;

namespace PassAppDev.Controllers
{
	[Authorize(Roles = Role.CUSTOMER)]
	public class CartBooksController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;
		public CartBooksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
		{
			_context = context;
			_userManager = userManager;
		}

		[HttpGet]
		public IActionResult Index()
		{
			var currentUserId = _userManager.GetUserId(HttpContext.User);
			IEnumerable<CartBook> booksInCart = _context.CartBooks
					 .Include(t => t.Book)
					 .Include(t => t.ApplicationUser)
					 .Where(t => t.ApplicationUserId == currentUserId)
					 .ToList();
			return View(booksInCart);
		}

		public async Task<IActionResult> AddToCart(int id)
		{
			var bookInStore = _context.Books.SingleOrDefault(t => t.Id == id);
			var currentUserId = _userManager.GetUserId(HttpContext.User);

			var bookInCart = _context.CartBooks.SingleOrDefault(
					t => t.ApplicationUserId == currentUserId &&
					t.BookId == id);
			if (bookInCart == null)
			{
				var cartBook = new CartBook()
				{
					ApplicationUserId = currentUserId,
					BookId = id,
					Quatity = 1,
					Price = bookInStore.Price
				};
				_context.Add(cartBook);
			}
			else
			{
				bookInCart.Quatity++;
			}
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}
		public async Task<IActionResult> Delete(int id)
		{

			var bookInCart = await _context.CartBooks.SingleOrDefaultAsync(t => t.Id == id);
			if (bookInCart == null)
			{
				return NotFound();
			}

			_context.CartBooks.Remove(bookInCart);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}


		public IActionResult IncreaseQty(int id)
		{
			var cartBookInDb = _context.CartBooks.SingleOrDefault(t => t.Id==id);
			if (cartBookInDb == null)
			{
				return NotFound();
			}

			cartBookInDb.Quatity ++;
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		public IActionResult DecreaseQty(int id)
		{
			var cartBookInDb = _context.CartBooks.SingleOrDefault(t => t.Id == id);
			if (cartBookInDb == null)
			{
				return NotFound();
			}
			if (cartBookInDb.Quatity > 0)
			{
				cartBookInDb.Quatity--;
			}
			
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

PassAppDev/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PassAppDev.Data;
using PassAppDev.Models;
using PassAppDev.Utils;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PassAppDev.Controllers
{
  [Authorize(Roles = Role.CUSTOMER)]
  public class OrdersController : Controller
    {
        private ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public OrdersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var currentUserId = _userManager.GetUserId(HttpContext.User);
            IEnumerable<Order> orders = _context.Orders
                .Where(t => t.ApplicationUserId == currentUserId)
                .Include(t=>t.ApplicationUser)
                .ToList();
            return View(orders);
        }


        public async Task<IActionResult> Order()
        {
            var currentUserId = _userManager.GetUserId(HttpContext.User);
            var booksInCart = _context.CartBooks.Where(t => t.ApplicationUserId == currentUserId).ToList();
            if (!booksInCart.Any())
            {
                return RedirectToAction("Index");
            }
            var newOrder = new Order
            {
                ApplicationUserId = currentUserId
            };
            _context.Add(newOrder);
            await _context.SaveChangesAsync();
            var orderInDb = _context.Orders.OrderByDescending(t => t.Id).First();
            var booksInOrder = new List<OrderedBook>();
            foreach (var item in booksInCart)
            {
                var newOrderedBook = new OrderedBook
                {
                    OrderId = orderInDb.Id,
                    BookId = item.BookId,
                    Quantity = item.Quatity,
                    Price = item.Price
                };
                booksInOrder.Add(newOrderedBook);
            }

            _context.OrderedBooks.AddRange(booksInOrder);
            _context.RemoveRange(booksInCart);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    [HttpGet]
    public IActionResult Details(int id)
		{
      IEnumerable<OrderedBook> orderedBooks = _context.OrderedBooks
                                              .Include(t=>t.Order)
                                              .Include(t=>t.Book)
                                              .Where(t=>t.OrderId==id)
                                              .ToList();
      return View(orderedBooks);
    }
    }
}

PassAppDev/Controllers/StoresController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using PassAppDev.Data;

using PassAppDev.Models;
using PassAppDev.Utils;
using PassAppDev.ViewModels;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;
using static System.Net.Mime.MediaTypeNames;

namespace PassAppDev.Controllers
{
    [Authorize(Roles = Role.STOREOWNER)]
    public class StoresController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public StoresController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        public IActionResult Index()
        {

            IEnumerable<Order> orders = _context.Orders
                                .Include(t => t.ApplicationUser)
                                .ToList();
            return View(orders);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            IEnumerable<OrderedBook> orderedBooks = _context.OrderedBooks
                                                                                            .Include(t => t.Order)
                                                                                            .Include(t => t.Book)
                                                                                            .Where(t => t.OrderId == id)
                                                                                            .ToList();
            return View(orderedBooks);
        }

        public IActionResult SearchUser(string email)
        {
            var customer = _userManager.GetUsersInRoleAsync(Role.CUSTOMER).Result;


            if (!string.IsNullOrWhiteSpace(email))
            {

                var result = customer.Where(t => t.Email.Contains(email)).ToList();

                return View(result);
            }


            return View(customer);

        }
    }
}

PassAppDev/Views/Shared/_Layout.cshtml
@using PassAppDev.Utils
@using PassAppDev.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PassAppDev</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap" rel="stylesheet">
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" style="font-size:1.5vw; color:#034ea2;" asp-area="" asp-controller="Home" asp-action="Index"><img class="img" style="width:6vw; height:3.5vw;" src="https://tinyurl.com/yc28tv7h" alt="...">Book</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse ">
                    <partial name="_LoginPartial" />
                    @if (!User.Identity.IsAuthenticated)
                    {

                        <form asp-controller="Home"
                          asp-action="Index"
                          method="GET"
                          style="margin-right:2vw;" class="form-inline my-2 my-lg-0 ">
                            <input class="form-control" type="text" name="keyWord" placeholder="Search by Category" />
                            <button type="submit" class="btn"><i style="font-size:1.5vw;" type="submit" class="bi bi-search"></i></button>
                        </form>
                    }
                    else if (User.IsInRole(Role.CUSTOMER))
                    {

                        <form asp-controller="Home"
                          asp-action="Index"
                          method="GET"
                          style="margin-right:2vw;" class="form-inline my-2 my-lg-0">
                            <input class="form-control" type="text" name="keyWord" placeholder="Search book" />
                            <button type="submit" class="btn"><i style="font-size:1.5vw;" type="submit" class="bi bi-search"></i></button>
                        </form>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a asp-controller="Orders" asp-action="Index" class="nav-link text-dark navbar-text">
                                    Orders
                                </a>
                            </li>
                        </ul>
                        <ul class="navbar-nav ">
                            <li class="nav-item">
                                <a asp-controller="CartBooks" asp-action="Index" class="nav-link text-dark navbar-text">
                                    <i class="bi bi-cart4"></i> Cart
                                </a>
                            </li>

                        </ul>
                    }


                    else if (User.IsInRole(Role.STOREOWNER))
                    {

                        <form asp-controller="Stores"
                          asp-action="SearchUser"
                          method="GET"
                          style="margin-right:2vw;" class="form-inline my-2 my-lg-0">
                            <input class="form-control" type="text" name="email" placeholder="Search Customers" />
                            <button type="submit" class="btn"><i style="font-size:1.5vw;" type="submit" class="bi bi-search"></i></button>
                        </form>
                        
                    }

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark navbar-text" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark navbar-text" asp-area="" asp-controller="Home" asp-action="HelpList">FAQs</a>
                        </li>
                    </ul>
                </div>
            </div>


        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PassAppDev - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>