PassAppDev/Models/Category.cs
using PassAppDev.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PassAppDev.Models
{
    public class Category
    {
     [Key]
     public int Id { get; set; }
     [Required(ErrorMessage = "Name cannot be null ...")]
     [StringLength(255)]
     public string Name { get; set; }
     public string OldName { get; set; }
     public DateTime CreatedAt { get; set; } = DateTime.Now;
     public CategoryStatus Status { get; set; } = CategoryStatus.Pending;

     public List<Book> Books { get; set; }

     public string ApplicationUserId { get; set; }
     public ApplicationUser ApplicationUser { get; set; }
  }
}

PassAppDev/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using PassAppDev.Data;
using PassAppDev.Models;
using PassAppDev.Utils;

using System.Collections.Generic;
using System.Linq;

namespace PassAppDev.Controllers
{

    [Authorize(Roles = Role.STOREOWNER)]
    public class CategoriesController : Controller
        {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public CategoriesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
           
        }
        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Category> categories = _context.Categories
                                                .Include(t=>t.ApplicationUser)
                                                .ToList();
            return View(categories);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Create(Category category)
        {
            var currentUserId = _userManager.GetUserId(HttpContext.User);
            if (!ModelState.IsValid)
                {
                    return View();
                }
            
            var newCategory = new Category
            {
                Name = category.Name,
                ApplicationUserId = currentUserId
            };

            _context.Add(newCategory);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var categoryInDb = _context.Categories.SingleOrDefault(t => t.Id == id);
            if (categoryInDb is null)
            {
                return NotFound();
            }

            return View(categoryInDb);
        }
        [HttpPost]
        public IActionResult Edit(Category category)
        {
            var categoryInDb = _context.Categories.SingleOrDefault(t => t.Id == category.Id);
            if (categoryInDb is null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(categoryInDb);
            }

            categoryInDb.OldName = categoryInDb.Name;
            categoryInDb.Name = category.Name;
            categoryInDb.Status = Enums.CategoryStatus.Pending;

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Notifications()
        {
            var currentUserId = _userManager.GetUserId(HttpContext.User);
            IEnumerable<Notification> notifications = _context.Notifications
                                                .Where(t => t.ApplicationUserId == currentUserId)
                                                .OrderByDescending(t => t.Id).Take(5)
                                                .ToList();
            return View(notifications);
        }
    }
}

PassAppDev/Views/Categories/Create.cshtml
@model Category

 <h1 class="text-center text-capitalize" style="color: #034ea2; font-size:4vw;">Create A New Category</h1>

<form asp-controller="Categories" asp-action="Create" method="post" style="width:55%;margin-left:18vw;">
  <div class="form-group font-weight-bold h5">
    <label>Category Name</label>
    <input asp-for="Name" class="form-control" placeholder="Category Name " />
    <span asp-validation-for="Name" class="text-danger font-weight-normal"></span>
  </div>
 
    <div class="form-group d-flex justify-content-between">
      <button type="reset" class="btn btn-danger">Cancel</button>
    <button type="submit" class="btn btn-primary">Create</button>
  </div>
</form>

PassAppDev/Views/Categories/Edit.cshtml
@model Category

<h1 class="text-center text-capitalize" style="color: #034ea2; font-size:3.5vw;">Edit Category Information</h1>

<form asp-controller="Categories" asp-action="Edit" method="post" style="width:55%;margin-left:16vw;">
  <input asp-for="Id" type="hidden" value="@Model.Id" />
  <div class="form-group font-weight-bold h5">
    <label>Category Name</label>
    <input asp-for="Name" class="form-control" placeholder="Category Name ..." />
    <span asp-validation-for="Name" class="text-danger"></span>
  </div>
  <div class="form-group d-flex justify-content-between">
      <button type="reset" class="btn btn-danger">Cancel</button>
    <button type="submit" class="btn btn-primary" onclick="return confirm('Are you sure you want to update the category: @Model.Name?')"
    >Confirm</button>
  </div>
</form>

PassAppDev/Views/Categories/Index.cshtml
<h1 class="text-center text-capitalize" style="color: #034ea2; font-size:3.5vw;">List Of Categories In Store</h1>

<div class="form-group">
  <a asp-controller="Categories" asp-action="Create" class="btn btn-primary"><i class="bi bi-list"></i>
    New Category
  </a>
</div>

<table class="table text-center">
  <thead>
    <tr>
      <th scope="col">Category Name</th>
      <th scope="col">Created At</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model){
      <tr>
      <th scope="row">@item.Name</th>
      <td>@item.CreatedAt</td>
      <td>@item.Status</td>
      <td>
        <a asp-controller="Categories" asp-action="Edit" asp-route-id=@item.Id class="btn btn-info"> 
          <i class="bi bi-pencil-square"></i> Edit
        </a>
      </td>
    </tr>
  }

  </tbody>
</table>